// This file can be replaced during build by using the `fileReplacements` array.
// `ng build ---prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  serverUrl: '/api',
  envName: 'DEV',
  // domain: 'http://localhost',
  domain: 'http://ec2-3-83-175-163.compute-1.amazonaws.com',

  authUrl: 'api/authentication/user/v1',
  authPort: '2001',
  investorUrl: 'api/investor/investor/v1',
  investorPort: '2002',
  entrepreneurUrl: 'api/entrepreneur/entrepreneur/v1',
  entrepreneurPort: '2003',
  autocompleteUrl: 'api/common/autocomplete/v1',
  autocompletePort: '2000'
};

/*
 * In development mode, to ignore zone related error stack frames such as
 * `zone.run`, `zoneDelegate.invokeTask` for easier debugging, you can
 * import the following file, but please comment it out in production mode
 * because it will have performance impact when throw error
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
